name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-version }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wucas/${{ matrix.gap-version }}:latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - gap-master-minimal
        GAP_PKGS_TO_CLONE: 
          - 'recog forms genss orb FactInt'
        GAP_PKGS_TO_DOWNLOAD: 
          - 'http://www.math.rwth-aachen.de/homes/Thomas.Breuer/atlasrep/atlasrep-2.1.2.tar.gz'
        include:
          - gap-version: gap-master-full
          - GAP_PKGS_TO_CLONE: ''
          - GAP_PKGS_TO_DOWNLOAD: ''

    steps:
      - uses: actions/checkout@v3
      - uses: wucas/setup-gap@v3
        with:
          GAP_PKGS_TO_CLONE: ${{matrix.GAP_PKGS_TO_CLONE}}
          GAP_PKGS_TO_DOWNLOAD: ${{matrix.GAP_PKGS_TO_DOWNLOAD}}
      - uses: gap-actions/build-pkg@v2
      - uses: wucas/run-pkg-tests@v3
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v2

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      - uses: actions/checkout@v3
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf
